name = "redraw_example"
target = "javascript"
version = "1.0.0"

description = ""
licences = ["MIT"]
links = [{title = "Sponsor", href = "https://github.com/sponsors/ghivert"}]
repository = {type = "github", user = "ghivert", repo = "sketch"}

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
redraw = {path = "../../../redraw/redraw"}
redraw_dom = {path = "../../../redraw/redraw_dom"}
sketch = {path = "../../sketch"}
sketch_redraw = {path = "../../sketch_redraw"}
shared_styles = {path = "../shared_styles"}

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
