name = "redraw_example"
target = "javascript"
version = "1.0.0"

description = ""
licences = ["MIT"]
links = [{title = "Sponsor", href = "https://github.com/sponsors/ghivert"}]
repository = {type = "github", user = "ghivert", repo = "sketch"}

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
redraw = ">= 1.1.0 and < 2.0.0"
redraw_dom = ">= 1.1.0 and < 2.0.0"
sketch = ">= 3.0.2 and < 4.0.0"
sketch_redraw = {path = "../../sketch_redraw"}
shared_styles = {path = "../shared_styles"}

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
