name = "sketch_lustre"
version = "2.0.0"

description = "A Sketch runtime package, made to work with Lustre!"
internal_modules = ["sketch/lustre/internals", "sketch/lustre/internals/*"]
licences = ["MIT"]
links = [{title = "Sponsor", href = "https://github.com/sponsors/ghivert"}]
gleam = ">= 1.6.0"

[repository]
type = "github"
user = "ghivert"
repo = "sketch"
path = "sketch_lustre"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.6.0 and < 5.0.0"
sketch = {path = "../sketch"}

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
