name = "sketch_lustre"
version = "1.0.2"

description = "A Sketch runtime package, made to work with Lustre!"
internal_modules = ["sketch/internals", "sketch/internals/*"]
licences = ["MIT"]
links = [{title = "Sponsor", href = "https://github.com/sponsors/ghivert"}]
repository = {type = "github", user = "ghivert", repo = "sketch"}

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.6.0 and < 5.0.0"
plinth = ">= 0.4.9 and < 1.0.0"
sketch = ">= 3.0.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
