name = "ssr"
version = "1.0.0"

[dependencies]
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 5.0.0 and < 6.0.0"
mist = "~> 4.0.0"
sketch = {path = "../../sketch"}
sketch_lustre_experimental = {path = "../../sketch_lustre_experimental"}
shared_view = {path = "../shared_view"}

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
