name = "web_application"
target = "javascript"
version = "1.0.0"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
lustre = ">= 4.6.0 and < 5.0.0"
sketch = { path = "../../sketch" }
sketch_lustre = { path = "../../sketch_lustre" }
shared_view = { path = "../shared_view" }

[dev-dependencies]
gleeunit = "~> 1.0"
lustre_dev_tools = ">= 1.4.2 and < 2.0.0"
