name = "sketch_lustre_experimental"
version = "0.2.0"

description = "An experimental Sketch runtime package, made to work with Lustre!"
internal_modules = ["sketch/lustre/expermental/internals", "sketch/lustre/experimental/internals/*"]
licences = ["MIT"]
links = [{title = "Sponsor", href = "https://github.com/sponsors/ghivert"}]
gleam = ">= 1.6.0"

[repository]
type = "github"
user = "ghivert"
repo = "sketch"
path = "sketch_lustre_experimental"

[dependencies]
gleam_stdlib = ">= 0.42.0 and < 2.0.0"
lustre = ">= 4.6.1 and < 5.0.0"
sketch = ">= 4.0.0 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
